package cn.jufangbao.house.shhouse.mapper;

import cn.jufangbao.house.shhouse.model.TCmAgentLhouse;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TCmAgentLhouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_agent_lhouse
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_agent_lhouse
     *
     * @mbg.generated
     */
    int insert(TCmAgentLhouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_agent_lhouse
     *
     * @mbg.generated
     */
    TCmAgentLhouse selectByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_agent_lhouse
     *
     * @mbg.generated
     */
    List<TCmAgentLhouse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_agent_lhouse
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCmAgentLhouse record);

    int deleteByAgentHouseID(@Param("oid") String oid, @Param("houseid")String houseid);
}